# Generated by Django 3.0.1 on 2020-08-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaryDashboard', '0003_colleges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colleges',
            new_name='College',
        ),
    ]
